# Prediction of Gene Expression from Histone Modification

Presenter: Jianjun Du

Department of Computer Science, University of Texas at Dallas

<h1>Introduction</h1>

<p>Basically, this is a classification problem. Histone modifications are important factors controlling gene expression. In this data set, five histone modifications were chosen as features to predict the gene expression level</p>
<p>The distinct characteristic is the combinatorial effect between different histone modifications.</p>
<p>The following classification algorithms will be used:</p>
<p>-----Support Vector Machine</p>
<p>-----Logistic Regression</p>
<p>-----Random Forest</p>
<p>-----Etreme gradient booster</p>
<p>-----Multiple layer neural network</p>
<p>-----Convolutional neural network</p>
<p></p>
<p>Especially I will introduce the principles of CNN</p>


![title](picture1.jpg)

In [1]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt

<h1>dataset exploring</h1>
<p>There are 15485 genes in the trainning dataset, and 100 bins and 5 diffrent histone modifications</p>
<p>This will generate 500 features for this classification problems.</p> 
<p>The predicted class is the gene expression level for each gene</p>

In [2]:
df=pd.read_csv('x_train.csv') # read the train data from the file

print("how many null values", df.isnull().values.sum()) #count the numbers of missing value in the data

data=df.iloc[:,1:6] # get rid of the GeneId column
mydata=data.values   #convert the data frame to numpy array
mydata=mydata.flatten() #convert the n-dimension array to one-dimension array

X=np.reshape(mydata,(15485,500)) #reshape the array so that there are 500 columns each row

print("The manipulated data is:")
print(X)
print("data shape: ",X.shape)

how many null values 0
The manipulated data is:
[[2 1 4 ..., 0 0 1]
 [1 0 1 ..., 0 0 0]
 [1 6 3 ..., 4 3 0]
 ..., 
 [0 2 1 ..., 2 0 1]
 [0 0 0 ..., 2 0 0]
 [2 0 0 ..., 0 2 1]]
data shape:  (15485, 500)


In [3]:
from sklearn import preprocessing
robust_scaler=preprocessing.RobustScaler()
x_train=robust_scaler.fit_transform(X)

In [4]:
df=pd.read_csv('y_train.csv')
df=df.iloc[:,1:2]
y_train=df.values
y=y_train.flatten()
print(y)
print(y.shape)

[0 0 1 ..., 0 0 0]
(15485,)


<h1>Model evaluation</h1>

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
# different models
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier,GradientBoostingClassifier,BaggingClassifier


<p>This function is used for evaluate the best parameters for a model with cross validation</P>

In [6]:
def model_parameters(X_train,y_train,model,tuned_parameters):
    
    scores = ['accuracy']

    for score in scores:
        print("# Tuning hyper-parameters for %s" % score)
        print()

        clf = GridSearchCV(model, tuned_parameters, cv=5,
                           scoring='%s' % score)
        clf.fit(X_train, y_train)

        print("Best parameters set found on development set:")
        print()
        print(clf.best_params_)
        print()
        print("Grid scores on development set:")
        print()
        means = clf.cv_results_['mean_test_score']
        stds = clf.cv_results_['std_test_score']
        for mean, std, params in zip(means, stds, clf.cv_results_['params']):
            print("%0.3f (+/-%0.03f) for %r"
                  % (mean, std * 2, params))
        print()

In [7]:
x_train, x_test, y_train, y_test = \
        train_test_split(X, y, test_size=.2, random_state=42)

In [8]:
# Neural network

tuned_parameters=[{'hidden_layer_sizes':[(100,),(10,20,5)],\
                   'activation':['relu','logistic'],'tol':[0.001],'max_iter':[1000]}]

model_parameters(x_train,y_train,MLPClassifier(),tuned_parameters)

# Tuning hyper-parameters for accuracy

Best parameters set found on development set:

{'activation': 'logistic', 'hidden_layer_sizes': (100,), 'max_iter': 1000, 'tol': 0.001}

Grid scores on development set:

0.821 (+/-0.018) for {'activation': 'relu', 'hidden_layer_sizes': (100,), 'max_iter': 1000, 'tol': 0.001}
0.816 (+/-0.008) for {'activation': 'relu', 'hidden_layer_sizes': (10, 20, 5), 'max_iter': 1000, 'tol': 0.001}
0.839 (+/-0.018) for {'activation': 'logistic', 'hidden_layer_sizes': (100,), 'max_iter': 1000, 'tol': 0.001}
0.833 (+/-0.010) for {'activation': 'logistic', 'hidden_layer_sizes': (10, 20, 5), 'max_iter': 1000, 'tol': 0.001}



In [9]:
# Logistic Regression

tuned_parameters=[{'penalty':['l1','l2'],'C':[200,150,100,20,1,0.5]}]

model_parameters(x_train,y_train,LogisticRegression(),tuned_parameters)

# Tuning hyper-parameters for accuracy

Best parameters set found on development set:

{'C': 1, 'penalty': 'l1'}

Grid scores on development set:

0.838 (+/-0.019) for {'C': 200, 'penalty': 'l1'}
0.838 (+/-0.020) for {'C': 200, 'penalty': 'l2'}
0.837 (+/-0.019) for {'C': 150, 'penalty': 'l1'}
0.837 (+/-0.019) for {'C': 150, 'penalty': 'l2'}
0.838 (+/-0.019) for {'C': 100, 'penalty': 'l1'}
0.837 (+/-0.019) for {'C': 100, 'penalty': 'l2'}
0.838 (+/-0.019) for {'C': 20, 'penalty': 'l1'}
0.838 (+/-0.019) for {'C': 20, 'penalty': 'l2'}
0.839 (+/-0.020) for {'C': 1, 'penalty': 'l1'}
0.838 (+/-0.019) for {'C': 1, 'penalty': 'l2'}
0.839 (+/-0.019) for {'C': 0.5, 'penalty': 'l1'}
0.838 (+/-0.019) for {'C': 0.5, 'penalty': 'l2'}



In [10]:
clf = RandomForestClassifier(random_state=0)
scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='accuracy') # using preprocessed data
scores

array([ 0.84665052,  0.84584342,  0.84140436,  0.8393866 ,  0.83077544])

In [11]:
scores = cross_val_score(clf, x_train, y_train, cv=5, scoring='accuracy') # using raw data
scores

array([ 0.84665052,  0.84584342,  0.84140436,  0.8393866 ,  0.83077544])

In [12]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression()
scores = cross_val_score(logreg,x_train,y_train,cv=10, scoring='accuracy')
scores

array([ 0.8377724 ,  0.87409201,  0.84665052,  0.82728006,  0.84745763,
        0.84180791,  0.84584342,  0.83292978,  0.81598063,  0.83993533])

In [13]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(100, 2), random_state=1)
scores = cross_val_score(clf,x_train,y_train,cv=5,scoring='accuracy')
scores

array([ 0.83414044,  0.84221146,  0.83535109,  0.82808717,  0.82310178])

In [14]:
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=6)
classifier1 = linear_model.LogisticRegression(penalty='l1',C=0.5)
classifier2 = SVC(kernel='linear', probability=True, random_state=1)
classifier3 = RandomForestClassifier(random_state=1)
classifier4 = MLPClassifier(alpha=1e-5, hidden_layer_sizes=(100,), random_state=1)

In [15]:
aucs = []
for train, test in cv.split(x_train, y_train):
    probas_ = classifier4.fit(x_train[train], y_train[train]).predict_proba(x_train[test])
    # Compute ROC curve and area the curve
    fpr, tpr, thresholds = roc_curve(y_train[test], probas_[:, 1])
    roc_auc = auc(fpr, tpr)
    aucs.append(roc_auc)
aucs



[0.8927733220768258,
 0.88522348857933497,
 0.89060081609680586,
 0.88299235495520845,
 0.8785141409877586,
 0.87347859840261055]

# Convolutional Neural Network

![title](picture7.jpg)

![title](picture8.jpg)

![title](picture3.jpg)

![title](picture2.jpg)

![title](picture4.jpeg)

![title](picture5.jpeg)

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

Using TensorFlow backend.


In [17]:
K.backend()

'tensorflow'

In [18]:
X=data.values.reshape(15485,100,5)

In [19]:
from sklearn.model_selection import train_test_split

df=pd.read_csv('y_train.csv')
df=df.iloc[:,1:2]
y=df.values
y=y.flatten()

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [20]:
batch_size = 128
num_classes = 2
epochs = 12

img_rows,img_cols=100,5

In [21]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

In [22]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (10374, 100, 5, 1)
10374 train samples
5111 test samples


In [23]:
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [24]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(2, 2),
                 activation='relu',
                 input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.15))
model.add(Conv2D(32, kernel_size=(2, 2),
                 activation='relu',
                 input_shape=input_shape))
model.add(Dropout(0.15))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 10374 samples, validate on 5111 samples
Epoch 1/12
10374/10374 [==============================] - 3s 337us/step - loss: 0.4763 - acc: 0.8113 - val_loss: 0.4019 - val_acc: 0.8366
Epoch 2/12
10374/10374 [==============================] - 2s 219us/step - loss: 0.4162 - acc: 0.8353 - val_loss: 0.3895 - val_acc: 0.8421
Epoch 3/12
10374/10374 [==============================] - 2s 220us/step - loss: 0.4042 - acc: 0.8418 - val_loss: 0.3970 - val_acc: 0.8429
Epoch 4/12
10374/10374 [==============================] - 2s 220us/step - loss: 0.3924 - acc: 0.8415 - val_loss: 0.3792 - val_acc: 0.8470
Epoch 5/12
10374/10374 [==============================] - 2s 220us/step - loss: 0.3880 - acc: 0.8458 - val_loss: 0.3815 - val_acc: 0.8499
Epoch 6/12
10374/10374 [==============================] - 2s 220us/step - loss: 0.3844 - acc: 0.8472 - val_loss: 0.3919 - val_acc: 0.8484
Epoch 7/12
10374/10374 [==============================] - 2s 225us/step - loss: 0.3804 - acc: 0.8487 - val_loss: 0.3759 - v